### ISSUE TITLE
Nest modules invitation

### ISSUE THREAD

**Issue by juandav** [svtslv/nestjs-mailer#2]
Hello, I see that you have been working on a module for emails, if you want we can integrate works, I can add you to the organization and work together.

https://github.com/nest-modules

**Comment by svtslv** [comment]
Hello, I tried to use your module, but I think the modules should be simple and with peer dependencies. This is a different ideology. If you have time and want to create something more than just a wrapper around nodemailer, what about notifications for nestjs?
https://github.com/notifme/notifme-sdk
https://github.com/laravel-notification-channels

**Comment by juandav** [comment]
Well, it would not only be for this module, it would be to build many more together, and enter into consensus on what should be integrated in each module.

**Comment by svtslv** [comment]
Thanks for the invite, you can add me, but I really don't have time, I just release modules that I use in my projects
